okul_bilisim_doi_generator:
  prefix:   /journal
  resource: "@OjsDoiBundle/Resources/config/routing/generator.yml"

okul_bilisim_doi_doi:
  prefix:   /
  resource: "@OjsDoiBundle/Resources/config/routing/doi.yml"

okul_bilisim_doi_config:
  prefix:   /journal
  resource: "@OjsDoiBundle/Resources/config/routing/config.yml"
