bulut_yazilim_doi_generator:
  prefix:   /journal/{journalId}/article/{id}
  resource: "@OjsDoiBundle/Resources/config/routing/generator.yml"

bulut_yazilim_doi_config:
  prefix:   /journal/{journalId}/doi-config
  resource: "@OjsDoiBundle/Resources/config/routing/config.yml"

bulut_yazilim_doi_crossref_pingback:
  path:     /crossref/pingback
  defaults: { _controller: "OjsDoiBundle:Doi:crossrefPingBack" }
  methods: [GET]
