bulut_yazilim_doi_config_update:
  path:     /
  defaults: { _controller: "OjsDoiBundle:Config:update" }
  methods: [PUT]

bulut_yazilim_doi_config_edit:
  path:     /
  defaults: { _controller: "OjsDoiBundle:Config:edit" }
  methods: [GET]
