okul_bilisim_doi_config_update:
  path:     /{journalId}/doi-config
  defaults: { _controller: "OjsDoiBundle:Config:update" }
  methods: [PUT]

okul_bilisim_doi_config_edit:
  path:     /{journalId}/doi-config
  defaults: { _controller: "OjsDoiBundle:Config:edit" }
  methods: [GET]
