bulut_yazilim_doi_doi_article_doi:
  path:     /journal/{journalId}/article/{id}/doi-send
  defaults: { _controller: "OjsDoiBundle:Doi:getArticleDoi" }
  methods: [GET]


bulut_yazilim_doi_crossref_pingback:
  path:     /crossref/pingback
  defaults: { _controller: "OjsDoiBundle:Doi:crossrefPingBack" }
  methods: [GET]
